# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

logger:
  default: info
  logs:
    custom_components.aguaiot: debug

recorder:
  purge_keep_days: 1
